export enum ErrorCode {
    NoError,
    ValidationError,
    GenericError,
    FailedGetConnection,
    ExternalRequestError,
    ParcialExecution,
    NothingChanged,
    IncidentsActions,
    Firebase,
    UnhandledRejection,
    SessionControl,
    SendingEmail,
    ExternalResource,
    CardsActions,
    PeopleActions,
    AzureTableStorage,
    UncaughtException
}
